name: fraud_analysis_env
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy=1.26.4
  - pandas=2.2.2
  - scikit-learn=1.5.1
  - matplotlib=3.9.2
  - seaborn=0.13.2
  - optuna=3.6.1
  - mlflow=2.16.0
  - boto3=1.34.162        # AWS SDK for Bedrock
  - requests=2.32.3
  - tqdm=4.66.5
  - pip
  - pip:
      - arize-phoenix==7.9.0
      - streamlit==1.38.0
      - sentence-transformers==3.1.1