channels:
- conda-forge
dependencies:
- python=3.11.9
- pip<=25.1.1
- pip:
  - mlflow==3.1.1
  - cloudpickle==3.1.1
  - numpy==2.3.1
  - pandas==2.3.1
  - psutil==7.0.0
  - scikit-learn==1.6.1
  - scipy==1.16.0
name: mlflow-env
